### ISSUE TITLE
meow-lwip fails to compile on Windows: bindgen 0.69 generates opaque structs for macro-defined fields

### ISSUE THREAD

**Issue by aimkiray** [madeye/mihomo-rust#471]
## Problem

`meow-lwip` (introduced in #411 / v0.21.0) fails to compile on Windows with 12 errors like:

```
error[E0609]: no field `remote_ip` on type `lwip::tcp_pcb`
  --> crates\meow-lwip\rust\core.rs:273:41
   |
273 |             util::to_socket_addr(&pcb_v.remote_ip, pcb_v.remote_port),
   |                                         ^^^^^^^^^ unknown field
   |
   = note: available field is: `_address`
```

Affected structs: `tcp_pcb`, `tcp_pcb_listen`, `netif`, `udp_pcb` — all generate as `pub struct tcp_pcb { pub _address: u8 }` (opaque), losing every real field.

## Root cause

`bindgen` 0.69 (the pinned build-dependency in `crates/meow-lwip/Cargo.toml`) fails to resolve struct layouts on Windows when fields are defined through C preprocessor macros. The affected structs use:

- `IP_PCB;` — expands to `local_ip`, `remote_ip`, `netif_idx`, `so_options`, `tos`, `ttl`
- `TCP_PCB_COMMON(type)` — expands to `next`, `callback_arg`, `state`, `prio`, `local_port`
- Direct fields in `struct netif` (`output`, `output_ip6`, `mtu`, `input`, etc.)

`clang -E` preprocessing confirms the C headers expand **correctly** — all fields are present after preprocessing. The bug is in bindgen 0.69's libclang type traversal on Windows: it treats these structs as incomplete (opaque) and emits `pub _address: u8` instead of the real fields.

bindgen 0.69 uses `clang-sys` with the `clang_6_0` feature; bindgen 0.72 upgraded to `clang_11_0`, which resolves the issue.

## Reproduction

```powershell
# Prerequisites: LLVM/clang installed, LIBCLANG_PATH set
cargo build --release -p meow-lwip
# 12 errors, all "no field X on type Y, available field is _address"
```

On Linux/macOS the same code compiles fine — bindgen 0.69 generates correct bindings there.

## Fix

Upgrade `bindgen` from 0.69 to 0.72 in `crates/meow-lwip/Cargo.toml`:

```diff
 [build-dependencies]
-bindgen = "0.69"
+bindgen = "0.72"
 cc = "1.0"
```

### API compatibility

All bindgen APIs used by `build.rs` are identical between 0.69 and 0.72:

| API | 0.69 | 0.72 |
|-----|------|------|
| `Builder::default()` | identical | identical |
| `.clang_arg()` | identical | identical |
| `.layout_tests(false)` | identical | identical |
| `.parse_callbacks(Box::new(CargoCallbacks::new()))` | identical | identical |
| `.size_t_is_usize(false)` | identical | identical |
| `.generate()` | identical | identical |
| `.write_to_file()` | identical | identical |

No changes needed in `build.rs` or any `rust/*.rs` file.

### Verification

After upgrading, all tests pass on Windows:

- `meow-lwip` unit tests: 2/2 pass
- `meow-lwip` integration tests (NetStack init, SYN packet processing, teardown): 2/2 pass
- `meow-listener` TUN module tests (wintun, dns, route, udp): 71/71 pass
- `cargo clippy --release`: zero warnings
