### ISSUE TITLE
meow-proxy v0.15.1 won't compile with the `anytls` feature — crates.io `anytls-rs` 0.5.4 has no `Stream::close()`

### ISSUE THREAD

**Issue by madeye** [madeye/mihomo-rust#262]
## Summary

`meow-proxy` fails to compile when the `anytls` feature is enabled, because it calls `anytls_rs::Stream::close()` but the dependency it resolves from crates.io — `anytls-rs = "0.5.4"` — does **not** provide that method.

The crates.io crate named `anytls-rs` (version 0.5.4) is **jxo-me's upstream crate** (`repository = https://github.com/jxo-me/anytls-rs`, author `Mickey <mickey@jxo.me>`), which has no `Stream::close()`. The `close()` method only exists in **madeye's fork** (`github.com/madeye/anytls-rs`), where it was added by the fd/stream-leak fix (madeye/anytls-rs#1). So a clean build against the registry cannot find it.

This affects anyone building meow-proxy with `anytls` from a clean registry (i.e. without the exact `Cargo.lock` shipped in this repo — and even that lock pins the same registry `0.5.4`).

## Reproduction

```sh
cargo build -p meow-proxy --features anytls
# or any downstream crate enabling meow-proxy/anytls or meow-config/anytls
```

## Error

```
error[E0599]: no method named `close` found for struct `Arc<anytls_rs::Stream>` in the current scope
   --> crates/meow-proxy/src/anytls_adapter.rs:259:21
    |
259 |         self.stream.close();
    |                     ^^^^^
...
   --> crates/meow-proxy/src/anytls_adapter.rs:270:21
    |
270 |         self.stream.close();
    |                     ^^^^^
error: could not compile `meow-proxy` (lib) due to 2 previous errors
```

## Root cause

`Cargo.toml` (workspace) declares:

```toml
# crates.io release of the madeye fork. 0.5.4 carries the `SocketProtector`
# registry + `connect_tcp` / `bind_udp` helpers (Android protect hook) and the
# fd/stream-leak fix for issue #201 item 4 (madeye/anytls-rs#1). ...
anytls-rs = { version = "0.5.4" }
```

The comment assumes crates.io `anytls-rs@0.5.4` is the madeye fork, but that crate name/version on crates.io belongs to jxo-me's upstream project and lacks `close()`. The breaking call (`self.stream.close()` in `anytls_adapter.rs`, the `poll_shutdown` / `Drop` paths) was introduced with the #201-item-4 leak fix in v0.14.0, so **v0.14.0 and v0.15.0/.1 are all affected** when the `anytls` feature is on.

Note: madeye/anytls-rs's own `v0.5.4` **git tag** also predates the `close()` merge (commit that merged madeye/anytls-rs#1) — so pinning that tag doesn't help either; only the fork commit that contains `Stream::close(&self)` works.

## Suggested fixes (pick one)

1. **Publish the fork to crates.io under a distinct name** (e.g. `anytls-meow`) and depend on that — keeps meow-proxy publishable to crates.io (the stated reason for requiring a registry version).
2. Depend on the fork **by git rev** that contains `close()` (works for building, but blocks `cargo publish` of meow-proxy).
3. Re-tag/publish the fork so the version meow-rs depends on actually contains `Stream::close()`.

## Workaround (for downstream consumers)

Add a patch pointing at the fork commit that merged the fix:

```toml
[patch.crates-io]
anytls-rs = { git = "https://github.com/madeye/anytls-rs", rev = "<commit that merged madeye/anytls-rs#1>" }
```

## Environment

- meow-rs: v0.15.1 (also v0.14.0, v0.15.0)
- Trigger: any build with feature `anytls` (e.g. `meow-config`/`meow-proxy` `anytls`, `ech-tls-tunnel`)
- Discovered while bumping an Android FFI consumer from meow-rs v0.13.0 → v0.15.1.
